# 1️⃣ Choose base image
FROM node

# 2️⃣ Create working directory inside container
WORKDIR /Backend

# 3️⃣ Copy package files
COPY package*.json ./

# 4️⃣ Install dependencies
RUN npm install

# 5️⃣ Copy rest of the project
COPY . .

# 6️⃣ Expose port
EXPOSE 5000

# 7️⃣ Start app
CMD ["npm", "start"]
